# yaml-language-server: $schema=../../handlers.schema.json
routes:
  - operationId: get_ip_report_reports_ip_report_get
    method: GET
    path: /reports/ip-report
    response:
      status: 200
      bodyTemplate:
        pagination:
          total_records: 1
          total_pages: 1
          current_page: 1
          page_size: 100
        data:
          - timestamp: "{{meta.now}}"
            destinationAccountId: "{{query.player_id}}"
            initiatorIpAddress: "{{query.ip_address}}"
            operationtype: login
            subtype: web
